SchoolAdministrator/Models/HomeViewModel.cs
using SchoolAdministrator.Data.Entities;

namespace SchoolAdministrator.Models
{
    public class HomeViewModel
    {
        public PaginatedList<Product> Products { get; set; }
        public float Quantity { get; set; }
        public ICollection<Subject> Subjects { get; set; }
    }
}

SchoolAdministrator/Models/ShowCartViewModel.cs
using SchoolAdministrator.Data.Entities;
using System.ComponentModel.DataAnnotations;

namespace SchoolAdministrator.Models
{
    public class ShowCartViewModel
    {
        public User User { get; set; }

        [DataType(DataType.MultilineText)]
        [Display(Name = "Comentarios")]
        public string? Remarks { get; set; }

        public ICollection<TemporalSale> TemporalSales { get; set; }

        [DisplayFormat(DataFormatString = "{0:N2}")]
        [Display(Name = "Cantidad")]
        public float Quantity => TemporalSales == null ? 0 : TemporalSales.Sum(ts => ts.Quantity);

        [DisplayFormat(DataFormatString = "{0:C2}")]
        [Display(Name = "Valor")]
        public decimal Value => TemporalSales == null ? 0 : TemporalSales.Sum(ts => ts.Value);
    }

}

SchoolAdministrator/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SchoolAdministrator.Data;
using SchoolAdministrator.Enums;
using SchoolAdministrator.Helpers;

namespace SchoolAdministrator.Controllers
{
    public class DashboardController : Controller
    {

        private readonly DataContext _context;
        private readonly IUserHelper _userHelper;

        public DashboardController(DataContext context, IUserHelper userHelper)
        {
            _context = context;
            _userHelper = userHelper;
        }


        public async Task<IActionResult> Index()
        {
            ViewBag.UsersCount = _context.Users.Count();
            //ViewBag.UsersCount = _context.Users.Where(t => t.EmailConfirmed == false).Count();
            ViewBag.ProductsCount = _context.Products.Count();
            ViewBag.NewOrdersCount = _context.Sales.Where(o => o.OrderStatus == OrderStatus.Nuevo).Count();
            ViewBag.ConfirmedOrdersCount = _context.Sales.Where(o => o.OrderStatus == OrderStatus.Confirmado).Count();
            ViewBag.InstitutionsCount = _context.Institutions.Count();
            ViewBag.SubjectsCount = _context.Subjects.Count();

            return View(await _context.TemporalSales
                    .Include(u => u.User)
                    .Include(p => p.Product).ToListAsync());
        }
    }

}

SchoolAdministrator/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SchoolAdministrator.Data;
using SchoolAdministrator.Data.Entities;
using SchoolAdministrator.Helpers;
using SchoolAdministrator.Models;
using Vereyon.Web;
using static SchoolAdministrator.Helpers.ModalHelper;

namespace SchoolAdministrator.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ProductsController : Controller
    {
        private readonly DataContext _context;
        private readonly ICombosHelper _combosHelper;
        private readonly IBlobHelper _blobHelper;
        private readonly IFlashMessage _flashMessage;

        public ProductsController(DataContext context, ICombosHelper combosHelper, IBlobHelper blobHelper, IFlashMessage flashMessage)
        {
            _context = context;
            _combosHelper = combosHelper;
            _blobHelper = blobHelper;
            _flashMessage = flashMessage;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.Products
                .Include(p => p.ProductImages)
                .Include(p => p.ProductCategories)
                .ThenInclude(pc => pc.Subject)
                .ToListAsync());
        }

        [NoDirectAccess]
        public async Task<IActionResult> Create()
        {
            CreateProductViewModel model = new()
            {
                Subjects = await _combosHelper.GetComboSubjectsAsync(),
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateProductViewModel model)
        {
            if (ModelState.IsValid)
            {
                Guid imageId = Guid.Empty;
                if (model.ImageFile != null)
                {
                    imageId = await _blobHelper.UploadBlobAsync(model.ImageFile, "products");
                }

                Product product = new()
                {
                    Description = model.Description,
                    Name = model.Name,
                    Price = model.Price,
                    Stock = model.Stock,
                };

                product.ProductCategories = new List<ProductCategory>()
                {
                    new ProductCategory
                    {
                        Subject = await _context.Subjects.FindAsync(model.SubjectId)
                    }
                };

                if (imageId != Guid.Empty)
                {
                    product.ProductImages = new List<ProductImage>()
                {
                    new ProductImage { ImageId = imageId }
                };
                }

                try
                {
                    _context.Add(product);
                    await _context.SaveChangesAsync();
                    _flashMessage.Confirmation("Registro creado.");
                    return Json(new
                    {
                        isValid = true,
                        html = ModalHelper.RenderRazorViewToString(this, "_ViewAllProducts", _context.Products
                        .Include(p => p.ProductImages)
                        .Include(p => p.ProductCategories)
                        .ThenInclude(pc => pc.Subject).ToList())
                    });

                }
                catch (DbUpdateException dbUpdateException)
                {
                    if (dbUpdateException.InnerException.Message.Contains("duplicate"))
                    {
                        _flashMessage.Info("Ya existe un producto con el mismo nombre.");
                    }
                    else
                    {
                        _flashMessage.Danger(dbUpdateException.InnerException.Message);
                    }
                }
                catch (Exception exception)
                {
                    _flashMessage.Danger(exception.Message);
                }
            }

            return Json(new { isValid = false, html = ModalHelper.RenderRazorViewToString(this, "Create", model) });

        }


        [NoDirectAccess]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Product product = await _context.Products.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }

            EditProductViewModel model = new()
            {
                Description = product.Description,
                Id = product.Id,
                Name = product.Name,
                Price = product.Price,
                Stock = product.Stock,
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, CreateProductViewModel model)
        {
            if (id != model.Id)
            {
                return NotFound();
            }

            try
            {
                Product product = await _context.Products.FindAsync(model.Id);
                product.Description = model.Description;
                product.Name = model.Name;
                product.Price = model.Price;
                product.Stock = model.Stock;
                _context.Update(product);
                await _context.SaveChangesAsync();
                _flashMessage.Confirmation("Registro actualizado.");
                return Json(new
                {
                    isValid = true,
                    html = ModalHelper.RenderRazorViewToString(this, "_ViewAllProducts", _context.Products
                    .Include(p => p.ProductImages)
                    .Include(p => p.ProductCategories)
                    .ThenInclude(pc => pc.Subject).ToList())
                });

            }
            catch (DbUpdateException dbUpdateException)
            {
                if (dbUpdateException.InnerException.Message.Contains("duplicate"))
                {
                    _flashMessage.Info("Ya existe un producto con el mismo nombre.");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, dbUpdateException.InnerException.Message);
                }
            }
            catch (Exception exception)
            {
                ModelState.AddModelError(string.Empty, exception.Message);
            }

            return Json(new { isValid = false, html = ModalHelper.RenderRazorViewToString(this, "Edit", model) });

        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Product product = await _context.Products
                .Include(p => p.ProductImages)
                .Include(p => p.ProductCategories)
                .ThenInclude(pc => pc.Subject)
                .FirstOrDefaultAsync(p => p.Id == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        [NoDirectAccess]
        public async Task<IActionResult> AddImage(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Product product = await _context.Products.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }

            AddProductImageViewModel model = new()
            {
                ProductId = product.Id,
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddImage(AddProductImageViewModel model)
        {
            if (ModelState.IsValid)
            {
                Guid imageId = Guid.Empty;
                if (model.ImageFile != null)
                {
                    imageId = await _blobHelper.UploadBlobAsync(model.ImageFile, "products");
                }

                Product product = await _context.Products.FindAsync(model.ProductId);
                ProductImage productImage = new()
                {
                    Product = product,
                    ImageId = imageId,
                };

                try
                {
                    _context.Add(productImage);
                    await _context.SaveChangesAsync();
                    return Json(new
                    {
                        isValid = true,
                        html = ModalHelper.RenderRazorViewToString(this, "Details", _context.Products
                    .Include(p => p.ProductImages)
                    .Include(p => p.ProductCategories)
                    .ThenInclude(pc => pc.Subject)
                    .FirstOrDefaultAsync(p => p.Id == model.ProductId))
                    });

                }
                catch (Exception exception)
                {
                    _flashMessage.Danger(exception.Message);
                }
            }

            return Json(new { isValid = false, html = ModalHelper.RenderRazorViewToString(this, "AddImage", model) });

        }

        public async Task<IActionResult> DeleteImage(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ProductImage productImage = await _context.ProductImages
                .Include(pi => pi.Product)
                .FirstOrDefaultAsync(pi => pi.Id == id);
            if (productImage == null)
            {
                return NotFound();
            }

            await _blobHelper.DeleteBlobAsync(productImage.ImageId, "products");
            _context.ProductImages.Remove(productImage);
            await _context.SaveChangesAsync();
            _flashMessage.Info("Registro borrado.");

SchoolAdministrator/Views/Home/Details.cshtml
@model SchoolAdministrator.Models.AddProductToCartViewModel

@{
    ViewData["Title"] = "Details";
}

<h1>@Model?.Name</h1>

<div class="row">
    <div class="col-md-6">
        <div id="ImagesCarousel" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
                @{
                    var first = true;
                }
                @foreach (var item in @Model?.ProductImages)
                {
                    <div class="carousel-item @(first?Html.Raw("active"):Html.Raw(""))">
                        <img class="d-block w-100" src="@item.ImageFullPath" alt="@item.Id">
                    </div>
                    first = false;
                }
            </div>
            <a id="ImagesCarouselPrev" class="carousel-control-prev" href="#ImagesCarousel" role="button"
               data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only btn btn-secondary">Anterior</span>
            </a>
            <a id="ImagesCarouselNext" class="carousel-control-next" href="#ImagesCarousel" role="button"
               data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only btn-primary btn">Siguiente</span>
            </a>
        </div>
    </div>
    <div class="col-md-6">
        <dl class="row">
            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.Description)
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.Description)
            </dd>
            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.Price)
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.Price)
            </dd>
            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.Stock)
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.Stock)
            </dd>
            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.Subjects)
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.Subjects)
            </dd>
            <div class="col-md-12">
                <form asp-action="Details">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="Id"/>
                    <div class="form-group">
                        <label asp-for="Remarks" class="control-label"></label>
                        <input asp-for="Remarks" class="form-control" />
                        <span asp-validation-for="Remarks" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Quantity" class="control-label"></label>
                        <input asp-for="Quantity" class="form-control" />
                        <span asp-validation-for="Quantity" class="text-danger"></span>
                    </div>
                    <div class="form-group mt-2">
                        <input type="submit" value="Agregar al Carro de Compras" class="btn btn-outline-primary" />
                        <a asp-action="Shop" class="btn btn-outline-success"><i class="fa-solid fa-arrow-rotate-left"></i> Regresar</a>
                    </div>
                </form>
            </div>
        </dl>
    </div>
</div>

@section Scripts {
    @{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
}
<script type="text/javascript">
    $(document).ready(function () {
        $("#ImagesCarousel").carousel();
        $("#ImagesCarouselPrev").click(function(){
            $("#ImagesCarousel").carousel("prev");
        });
        $("#ImagesCarouselNext").click(function(){
            $("#ImagesCarousel").carousel("next");
        });
    });
</script>
}

SchoolAdministrator/Views/Home/Edit.cshtml
@model SchoolAdministrator.Models.EditTemporalSaleViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Editar</h1>

<h4>Carro de Compras</h4>
<hr />
<div class="row">
    <div class="col-md-12">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Remarks" class="control-label"></label>
                <input asp-for="Remarks" class="form-control" />
                <span asp-validation-for="Remarks" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group mt-2">
                <input type="submit" value="Guardar" class="btn btn-outline-primary" />
                <a asp-action="ShowCart" class="btn btn-outline-success"><i class="fa-solid fa-arrow-rotate-left"></i> Regresar</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SchoolAdministrator/Views/Home/Error404.cshtml
@{
	ViewData["Title"] = "Error404";
}

<br />
<br />
<center><img src="~/images/nofound.png" width="70%" height="70%" /></center>
<center><h2>Error, página no encontrada</h2></center>

SchoolAdministrator/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<flash dismissable="true" />
<div class="text-center">
    <center><img src="~/images/welcomeTo.png" width="70%" height="100%" /></center>
</div>

<div class="text-center mb-5">
    @if (User.Identity.IsAuthenticated != true || User.IsInRole("User"))
    {
        <a class="btn btn-outline-primary" asp-controller="Home" asp-action="Shop"><i class="fa-solid fa-store"></i> Tienda</a>
    }
    
    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
    {
        <a class="btn btn-outline-primary" asp-controller="Products" asp-action="Index"><i class="fa-solid fa-store"></i> Productos</a>
        <a class="btn btn-outline-dark" asp-controller="Dashboard" asp-action="Index"><i class="fa fa-tachometer-alt text-danger"></i> Dashboard</a>
    }

</div>

SchoolAdministrator/Views/Home/OrderSuccess.cshtml
@{
    ViewData["Title"] = "Order Success";
}


<div class="row">
    @*<img src="~/images/welcomeTo.png"/>*@
    <div class="text-center">
        <h2><i class="fa-solid fa-circle-check btn-outline-success"></i> Pedido confirmado!!</h2>
        <h4>Muchas gracias su pedido fue registrado en nuestro sistema, recuerda que tu pedido será enviado a la institución educativa que perteneces.</h4>
        <br />  
        <a asp-action="Shop" class="mt-2 btn btn-outline-success">Aceptar</a>
    </div>
</div>

SchoolAdministrator/Views/Home/Shop.cshtml
@model SchoolAdministrator.Models.HomeViewModel

@{
    ViewData["Title"] = "Shop";
}

<section class="vh-90">
    <style type="text/css">
        .card {
            display: flex;
            flex-direction: column;
            justify-content: space-between;
            border: 1px solid lightgray;
            box-shadow: 2px 2px 8px 4px #d3d3d3d1;
            border-radius: 15px;
            font-family: sans-serif;
            margin: 5px;
        }
    </style>


    <flash dismissable="true" />
    <h1><i class="fa-solid fa-book-bookmark"></i> Administrador Escolar</h1>
    <h3>Materias</h3>

    <div class="mb-2">
        @foreach (var item in Model.Subjects)
        {
            <span> <a class="btn btn-outline-primary" href="@Url.Action("Shop", "Home", new { searchString = item.Name})" ><strong> @item.Name&nbsp;</strong></a></span>
        }
    </div>

    @if (Model.Quantity > 0)
    {
        <a asp-action="ShowCart" class="btn btn-outline-primary"><i class="fa-solid fa-cart-shopping"></i> (@Model.Quantity)</a>
    }

    <form asp-action="Shop" method="get" class="mt-2">
        <div class="form-actions no-color">
            <p>
                Buscar por nombre o materia: <input type="text" name="SearchString" value="@ViewData["CurrentFilter"]" />
                    <input type="submit" value="Buscar" class="btn btn-outline-dark" /> 
                <a asp-action="Shop" class="btn btn-outline-dark"><i class="fa-solid fa-eye"></i> Todos los Productos</a>
            </p>
        </div>
    </form>

     <div class="mb-2 mt-2">
        <a asp-action="Shop" class="btn btn-outline-secondary" asp-route-sortOrder="@ViewData["NameSortParm"]"><i class="fa-solid fa-sort"></i> Ordenar por Nombre</a>&nbsp;&nbsp;
        <a asp-action="Shop" class="btn btn-outline-secondary" asp-route-sortOrder="@ViewData["PriceSortParm"]"><i class="fa-solid fa-sort"></i> Ordenar por Precio</a>
    </div>


    <div class="row row-cols-1 row-cols-md-4 g-4 mt-1">
        @if (Model.Products.Count() > 0)
        {
            @foreach (var item in Model.Products)
            {
                <div class="col">
                    <div class="card h-100">
                        <div class="text-center zoom mt-2">
                            <img src="@item.ImageFullPath" style="height:200px; max-width:230px;" class="text-center" alt=@item.Name />
                        </div>
                        <div class="card-body text-center">
                            <h5 class="card-title text-navy"> @item.Name</h5>
                            <p class="card-text smfnt">@item.Description</p>
                            <h5 class="text-muted">@Html.DisplayFor(modelItem => item.Price)</h5>
                        </div>
                        <div class="card-footer text-center">
                            <a asp-action="Details" asp-route-id="@item.Id" class="btn btn btn-secondary"><i class="fa-solid fa-circle-info"></i></a>
                            <a asp-action="Add" asp-route-id="@item.Id" class="btn btn btn-primary"><i class="fa-solid fa-circle-plus"></i></a>
                        </div>
                    </div>
                </div>
            }
        }
        else
        {
            <h3><i class="fa-solid fa-circle-info"></i> No hay productos con su criterio de búsqueda</h3>
        }
    </div>

    @{
        var prevDisabled = !Model.Products.HasPreviousPage ? "disabled" : "";
        var nextDisabled = !Model.Products.HasNextPage ? "disabled" : "";
    }

    <div class="mt-5 text-center">
        <a asp-action="Shop"
           asp-route-sortOrder="@ViewData["CurrentSort"]"
           asp-route-pageNumber="@(Model.Products.PageIndex - 1)"
           asp-route-currentFilter="@ViewData["CurrentFilter"]"
           class="btn btn-outline-dark @prevDisabled">
            <i class="fa-solid fa-circle-chevron-left"></i>
        </a>
        <a asp-action="Shop"
           asp-route-sortOrder="@ViewData["CurrentSort"]"
           asp-route-pageNumber="@(Model.Products.PageIndex + 1)"
           asp-route-currentFilter="@ViewData["CurrentFilter"]"
           class="btn btn-outline-dark @nextDisabled">
            <i class="fa-solid fa-circle-chevron-right"></i>
        </a>
    </div>


    @section Scripts {
    @{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }
</section>

SchoolAdministrator/Views/Home/ShowCart.cshtml
@model SchoolAdministrator.Models.ShowCartViewModel

@{
    ViewData["Title"] = "Cart";
}



<div class="row">
    <div class="col-md-4">
        <dl class="row border">
            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.Quantity)
            </dt>
            <dd class="col-sm-8">
                <h3>@Html.DisplayFor(model => model.Quantity)</h3>
            </dd>
            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.Value)
            </dt>
            <dd class="col-sm-8">
                <h3>@Html.DisplayFor(model => model.Value)</h3>
            </dd>
        </dl>
    </div>
    <div class="col-md-8">
        <div class="col-md-12">
            <form asp-action="ShowCart">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Remarks" class="control-label"></label>
                    <input asp-for="Remarks" class="form-control" />
                    <span asp-validation-for="Remarks" class="text-danger"></span>
                </div>
                <div class="form-group mt-2">
                    <input type="submit" value="Confirmar Pedido" class="btn btn-outline-primary" />
                    <a asp-action="Shop" class="btn btn-outline-success"><i class="fa-solid fa-arrow-rotate-left"></i> Regresar</a>
                </div>
            </form>
        </div>
    </div>
</div>


<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Carro de Compras</h3>
            </div>
            <div class="panel-body">
                <table class="table table-hover table-responsive text-center table-striped" id="MyTable">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.TemporalSales.FirstOrDefault().Product.ImageFullPath)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.TemporalSales.FirstOrDefault().Product.Name)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.TemporalSales.FirstOrDefault().Remarks)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.TemporalSales.FirstOrDefault().Product.Price)
                            </th>
                            <th></th>
                            <th>
                                @Html.DisplayNameFor(model => model.TemporalSales.FirstOrDefault().Quantity)
                            </th>
                            <th></th>
                            <th>
                                @Html.DisplayNameFor(model => model.TemporalSales.FirstOrDefault().Value)
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.TemporalSales)
                        {
                            <tr>
                                <td>
                                    <div class="zoom">
                                        <img src="@item.Product.ImageFullPath" style="width:100px;" />
                                    </div>
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Product.Name)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Remarks)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Product.Price)
                                </td>
                                <td>
                                    <a asp-action="DecreaseQuantity" asp-route-id="@item.Id" class="btn btn-outline-secondary"><i class="fa-solid fa-minus"></i></a>
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Quantity)
                                </td>
                                <td>
                                    <a asp-action="IncreaseQuantity" asp-route-id="@item.Id" class="btn btn-outline-primary"><i class="fa-solid fa-circle-plus"></i></a>
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Value)
                                </td>
                                <td>
                                    <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-outline-secondary"><i class="fa-solid fa-pen-to-square"></i></a>
                                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-outline-danger"><i class="fa-solid fa-circle-minus"></i></a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
}


<script type="text/javascript">
    $(document).ready(function () {
        $('#MyTable').DataTable({
            "language": {
                "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json"
            },
            "aLengthMenu": [
                [25, 50, 100, 200, -1],
                [25, 50, 100, 200, "Todos"]
            ]
        });
    });
</script>
}