SchoolAdministrator/Models/LevelViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace SchoolAdministrator.Models
{
    public class LevelViewModel
    {
        public int Id { get; set; }


        [Display(Name = "Nivel")]
        [MaxLength(45, ErrorMessage = "El campo {0} debe tener maximo {1} caractéres.")]
        [Required(ErrorMessage = "El campo {0} es obligatorio.")]
        public String Name { get; set; }


        [Display(Name = "Tipo de Nivel")]
        [MaxLength(45, ErrorMessage = "El campo {0} debe tener maximo {1} caractéres.")]
        [Required(ErrorMessage = "El campo {0} es obligatorio.")]
        public String Type { get; set; }
        
        public int InstitutionId { get; set; }
    }
}

SchoolAdministrator/Controllers/InstitutionsController.cs
#nullable disable
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SchoolAdministrator.Data;
using SchoolAdministrator.Data.Entities;
using SchoolAdministrator.Helpers;
using SchoolAdministrator.Models;
using Vereyon.Web;
using static SchoolAdministrator.Helpers.ModalHelper;

namespace SchoolAdministrator.Controllers
{
    [Authorize(Roles = "Admin")]
    public class InstitutionsController : Controller
    {
        private readonly DataContext _context;
        private readonly IFlashMessage _flashMessage;

        public InstitutionsController(DataContext context, IFlashMessage flashMessage)
        {
            _context = context;
            _flashMessage = flashMessage;
        }

        // GET: Institutions
        public async Task<IActionResult> Index()
        {
            return View(await _context.Institutions
                .Include(i => i.Levels)
                .ToListAsync());
        }

        // GET: Institutions/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var institution = await _context.Institutions
                .Include(i => i.Levels)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (institution == null)
            {
                return NotFound();
            }

            return View(institution);
        }


        public async Task<IActionResult> DetailsLevel(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Level level = await _context.Levels
                .Include(i => i.Institution)
                .FirstOrDefaultAsync(l => l.Id == id);
            if (level == null)
            {
                return NotFound();
            }

            return View(level);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Institution institution)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Add(institution);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                catch (DbUpdateException dbUpdateException)
                {
                    if (dbUpdateException.InnerException.Message.Contains("duplicate"))
                    {
                        _flashMessage.Info("Ya existe una Institución con el mismo nombre.");
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, dbUpdateException.InnerException.Message);
                    }
                }
                catch (Exception exception)
                {
                    ModelState.AddModelError(string.Empty, exception.Message);
                }
            }
            return View(institution);

        }


        [NoDirectAccess]
        public async Task<IActionResult> AddLevel(int id)
        {
            Institution institution = await _context.Institutions.FindAsync(id);
            if (institution == null)
            {
                return NotFound();
            }

            LevelViewModel model = new()
            {
                InstitutionId = institution.Id,
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddLevel(LevelViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    Level level = new()
                    {
                        Institution = await _context.Institutions.FindAsync(model.InstitutionId),
                        Name = model.Name,
                        Type = model.Type,
                    };
                    _context.Add(level);
                    await _context.SaveChangesAsync();
                    Institution institution = await _context.Institutions
                        .Include(c => c.Levels)
                        .FirstOrDefaultAsync(c => c.Id == model.InstitutionId);
                    _flashMessage.Info("Registro creado");
                    return Json(new { isValid = true, html = ModalHelper.RenderRazorViewToString(this, "_ViewAllLevels", institution) });
                }
                catch (DbUpdateException dbUpdateException)
                {
                    if (dbUpdateException.InnerException.Message.Contains("duplicate"))
                    {
                        _flashMessage.Info("Ya existe un Nivel con el mismo nombre en esta Institución.");
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, dbUpdateException.InnerException.Message);
                    }
                }
                catch (Exception exception)
                {
                    ModelState.AddModelError(string.Empty, exception.Message);
                }
            }

            return Json(new { isValid = false, html = ModalHelper.RenderRazorViewToString(this, "AddLevel", model) });

        }


        [NoDirectAccess]
        public async Task<IActionResult> EditLevel(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Level level = await _context.Levels
                .Include(l => l.Institution)
                .FirstOrDefaultAsync(l => l.Id == id);
            if (level == null)
            {
                return NotFound();
            }

            LevelViewModel model = new()
            {
                InstitutionId = level.Institution.Id,
                Id = level.Id,
                Name = level.Name,
                Type = level.Type
            };

            return View(model);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditLevel(int id, LevelViewModel model)
        {
            if (id != model.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    Level level = await _context.Levels.FindAsync(model.Id);
                    level.Name = model.Name;
                    level.Type = model.Type;

                    _context.Update(level);
                    Institution institution = await _context.Institutions
                        .Include(c => c.Levels)
                        .FirstOrDefaultAsync( c => c.Id == model.InstitutionId);
            
                    await _context.SaveChangesAsync();
                    return Json(new { isValid = true, html = ModalHelper.RenderRazorViewToString(this, "_ViewAllLevels", institution) });
                }

                catch (DbUpdateException dbUpdateException)
                {
                    if (dbUpdateException.InnerException.Message.Contains("duplicate"))
                    {
                        _flashMessage.Info("Ya existe un Nivel con el mismo nombre en esta Institución.");
                    }
                    else
                    {
                        _flashMessage.Danger(dbUpdateException.InnerException.Message);
                    }
                }
                catch (Exception exception)
                {
                    _flashMessage.Danger(exception.Message);
                }
            }

            return Json(new { isValid = false, html = ModalHelper.RenderRazorViewToString(this, "EditLevel", model) });

        }


        private bool InstitutionExists(int id)
        {
            return _context.Institutions.Any(e => e.Id == id);
        }

        public async Task<IActionResult> DeleteLevel(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var level = await _context.Levels
                .Include(s => s.Institution)
                .FirstOrDefaultAsync(s => s.Id == id);
            if (level == null)
            {
                return NotFound();
            }

            try
            {
                _context.Levels.Remove(level);
                await _context.SaveChangesAsync();
                _flashMessage.Info("Registro borrado.");
            }
            catch
            {
                _flashMessage.Danger("No se puede borrar el nivel porque tiene registros relacionados.");
            }

            return RedirectToAction(nameof(Details), new { Id = level.Institution.Id });
        }



        [HttpPost, ActionName("DeleteLevel")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteLevelConfirmed(int id)
        {
            Level level = await _context.Levels
                .Include(l => l.Institution)
                .FirstOrDefaultAsync(l => l.Id == id);
            _context.Levels.Remove(level);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Details), new { Id = level.Institution.Id });
        }


        [NoDirectAccess]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Institution institution = await _context.Institutions.FirstOrDefaultAsync(c => c.Id == id);
            if (institution == null)
            {
                return NotFound();
            }

            try
            {
                _context.Institutions.Remove(institution);
                await _context.SaveChangesAsync();
                _flashMessage.Info("Registro borrado.");
            }
            catch
            {

SchoolAdministrator/Controllers/LevelsController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SchoolAdministrator.Data;
using SchoolAdministrator.Data.Entities;
using Vereyon.Web;

namespace SchoolAdministrator.Controllers
{
    public class LevelsController : Controller
    {
        private readonly DataContext _context;
        private readonly IFlashMessage _flashMessage;

        public LevelsController(DataContext context, IFlashMessage flashMessage)
        {
            _context = context;
            _flashMessage = flashMessage;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Levels.ToListAsync());
        }

        [HttpGet]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Level level = await _context.Levels
                .FirstOrDefaultAsync(m => m.Id == id);
            if (level == null)
            {
                return NotFound();
            }

            return View(level);
        }


        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Level level)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Add(level);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                catch (DbUpdateException dbUpdateException)
                {
                    if (dbUpdateException.InnerException.Message.Contains("duplicate"))
                    {
                        _flashMessage.Info("Ya existe un Nivel con el mismo nombre.");
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, dbUpdateException.InnerException.Message);
                    }
                }
                catch (Exception exception)
                {
                    ModelState.AddModelError(string.Empty, exception.Message);
                }
            }

            return View(level);

    }


    public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Level level = await _context.Levels.FindAsync(id);
            if (level == null)
            {
                return NotFound();
            }

            return View(level);
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Level level)
        {
            if (id != level.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(level);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                catch (DbUpdateException dbUpdateException)
                {
                    if (dbUpdateException.InnerException.Message.Contains("duplicate"))
                    {
                        _flashMessage.Info("Ya existe un Nivel con el mismo nombre.");
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, dbUpdateException.InnerException.Message);
                    }
                }
                catch (Exception exception)
                {
                    ModelState.AddModelError(string.Empty, exception.Message);
                }

            }
            return View(level);
        }

   
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Level level = await _context.Levels.FindAsync(id);
            if (level == null)
            {
                return NotFound();
            }

            return View(level);
        }

        
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            Level level = await _context.Levels.FindAsync(id);
            _context.Levels.Remove(level);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

    }
}

SchoolAdministrator/Views/Institutions/AddLevel.cshtml
@model SchoolAdministrator.Models.LevelViewModel

@{
    ViewData["Title"] = "Nivel";
    Layout = null;
}

<flash dismissable="true" />

<div class="container smfont">
    <form asp-action="AddLevel" autocomplete="off" asp-route-id="@Model.Id" onsubmit="return jQueryAjaxPost(this);">
        <div class="box-body">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="InstitutionId" />

            <partial name="_Level" />

        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-sm btn-primary" data-bs-dismiss="modal"><i class="fa fa-ban"></i> Cancelar</button>
            <button type="submit" class="btn btn-sm btn-success"><i class="fa fa-save"></i> Guardar</button>
        </div>
    </form>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SchoolAdministrator/Views/Institutions/AddOrEdit.cshtml
@model SchoolAdministrator.Data.Entities.Institution

@{
    ViewData["Title"] = "País";
    Layout = null;
}

<flash dismissable="true" />

<div class="container smfont">
    <form asp-action="AddOrEdit" autocomplete="off" asp-route-id="@Model.Id" onsubmit="return jQueryAjaxPost(this);">
        <div class="box-body">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <span class="required">*</span>
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control smfont" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <span class="required">*</span>
                <label asp-for="InstitutionType" class="control-label"></label>
                <input asp-for="InstitutionType" class="form-control smfont" />
                <span asp-validation-for="InstitutionType" class="text-danger"></span>
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-sm btn-primary" data-bs-dismiss="modal"><i class="fa fa-ban"></i> Cancelar</button>
            <button type="submit" class="btn btn-sm btn-success"><i class="fa fa-save"></i> Guardar</button>
        </div>
    </form>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SchoolAdministrator/Views/Institutions/DeleteLevel.cshtml
@model SchoolAdministrator.Data.Entities.Level

@{
    ViewData["Title"] = "Delete Level";
}

<h1>Eliminar</h1>

<h3>¿Estás seguro de eliminar?</h3>
<div>
    <h4>Nivel</h4>
    <hr />
    <partial name="_LevelDetails" />    
    <form asp-action="DeleteLevel">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Eliminar" class="btn btn-outline-danger" />
        <a asp-action="Details" asp-route-id="@Model?.Institution.Id" class="btn btn-outline-success"><i class="fa-solid fa-arrow-rotate-left"></i> Regresar</a>
    </form>
</div>

SchoolAdministrator/Views/Institutions/Details.cshtml
@model SchoolAdministrator.Data.Entities.Institution

@{
    ViewData["Title"] = "Details";
}

<flash dismissable="true" />

<h3><i class="fa-solid fa-circle-info text-primary"></i> Detalles</h3>

<div>
    <partial name="_InstitutionDetails" />    
</div>

<div>
    <a asp-action="Index" class="btn btn-outline-success"><i class="fa-solid fa-arrow-rotate-left"></i> Regresar</a>
</div>
<hr />

<!-- Content Wrapper. Contains page content -->
<div class="container-fluid">
    <div class="card mt-2">
        <div class="card-header text-dark text-center">
            <i class="fa-solid fa-layer-group text-danger"></i>  <strong> Niveles</strong>
        </div>
        <div class="card-body">
            <div id="view-all">
                @await Html.PartialAsync("_ViewAllLevels", Model)
            </div>
        </div>
    </div>
</div>

<partial name="_AddOrEditDialog" />
<partial name="_DeleteDialog" />

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script src="~/js/showmodal.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#LevelsTable').DataTable({
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json"
                },
                "aLengthMenu": [
                    [25, 50, 100, 200, -1],
                    [25, 50, 100, 200, "Todos"]
                ]
            });
        });
    </script>

    <script>
        sc_deleteDialog.openModal('deleteItem', true, 'btnYesDelete', '/Institutions/DeleteLevel/', false);
    </script>
}

SchoolAdministrator/Views/Institutions/DetailsLevel.cshtml
@model SchoolAdministrator.Data.Entities.Level

@{
    ViewData["Title"] = "Level Details";
}


<h3><i class="fa-solid fa-circle-info text-primary"></i> Detalles Nivel</h3>

<div>
    <hr />
    <partial name="_LevelDetails" />

</div>
<div>
    <a asp-action="Details" asp-route-id="@Model?.Institution.Id" class="btn btn-outline-success"><i class="fa-solid fa-arrow-rotate-left"></i> Regresar</a>
</div>

SchoolAdministrator/Views/Institutions/EditLevel.cshtml
@model SchoolAdministrator.Models.LevelViewModel

@{
    ViewData["Title"] = "Nivel";
    Layout = null;
}

<flash dismissable="true" />

<div class="container smfont">
    <form asp-action="EditLevel" autocomplete="off" asp-route-id="@Model.Id" onsubmit="return jQueryAjaxPost(this);">
        <div class="box-body">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="InstitutionId" />

            <partial name="_Level"/>

        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-sm btn-primary" data-bs-dismiss="modal"><i class="fa fa-ban"></i> Cancelar</button>
            <button type="submit" class="btn btn-sm btn-success"><i class="fa fa-save"></i> Guardar</button>
        </div>
    </form>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SchoolAdministrator/Views/Institutions/Index.cshtml
@model IEnumerable<SchoolAdministrator.Data.Entities.Institution>

@{
    ViewData["Title"] = "Index";
}

<flash dismissable="true" />

<!-- Content Wrapper. Contains page content -->
<div class="container-fluid text-center">
    <div class="card mt-2">
        <div class="card-header text-dark">
            <i class="fa-solid fa-graduation-cap text-warning"></i>  <strong>Instituciones</strong>
        </div>
        <div class="card-body">
            <div id="view-all">
                @await Html.PartialAsync("_ViewAll", Model)
            </div>
        </div>
    </div>
</div>

<partial name="_AddOrEditDialog" />
<partial name="_DeleteDialog" />

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script src="~/js/showmodal.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#InstitutionsTable').DataTable({
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json"
                },
                "aLengthMenu": [
                    [25, 50, 100, 200, -1],
                    [25, 50, 100, 200, "Todos"]
                ]
            });
        });
    </script>

    <script>
        sc_deleteDialog.openModal('deleteItem', true, 'btnYesDelete', '/Institutions/Delete/', false);
    </script>
}

SchoolAdministrator/Views/Institutions/_AddOrEditDialog.cshtml
<div class="modal fade in" tabindex="-1" role="dialog" data-bs-backdrop="static" id="form-modal">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header bg-primary">
                <h5 class="modal-title text-white"></h5>
                <button type="button" class="btn-close text-white" data-bs-dismiss="modal" aria-label="Close">                   
                </button>
            </div>
            <div class="modal-body">
            </div>
        </div>
    </div>
</div>

SchoolAdministrator/Views/Institutions/_InstitutionDetails.cshtml
@model SchoolAdministrator.Data.Entities.Institution


<dl class="row">
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Name)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Name)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.InstitutionType)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.InstitutionType)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.LevelsNumber)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.LevelsNumber)
    </dd>
</dl>

SchoolAdministrator/Views/Institutions/_Level.cshtml
@model SchoolAdministrator.Models.LevelViewModel

<div class="form-group">
    <span class="required">*</span>
    <label asp-for="Name" class="control-label"></label>
    <input asp-for="Name" class="form-control" />
    <span asp-validation-for="Name" class="text-danger"></span>
</div>
<div class="form-group">
    <span class="required">*</span>
    <label asp-for="Type" class="control-label"></label>
    <input asp-for="Type" class="form-control" />
    <span asp-validation-for="Type" class="text-danger"></span>
</div>

SchoolAdministrator/Views/Institutions/_LevelDetails.cshtml
@model SchoolAdministrator.Data.Entities.Level


<dl class="row">
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Name)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Name)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Type)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Type)
    </dd>
    
</dl>

SchoolAdministrator/Views/Institutions/_ViewAll.cshtml
@model IEnumerable<SchoolAdministrator.Data.Entities.Institution>

<flash dismissable="true" />

<table class="table table-striped table-responsive-md table-bordered smfont"  id="InstitutionsTable">
    <colgroup>
        <col span="1" />
        <col span="1" />
        <col span="1" />
    </colgroup>
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.InstitutionType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LevelsNumber)
            </th>
            <th>
                <a onclick="showInPopup('@Url.Action("AddOrEdit", "Institutions", new { id = 0 }, Context.Request.Scheme)' , 'Nueva institución')" class="btn btn-primary text-white"><i class="fa fa-plus-circle"></i> Institución</a>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                <a asp-action="Details" asp-controller="Institutions" asp-route-Id="@item.Id">@Html.DisplayFor(modelItem => item.Name)</a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.InstitutionType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LevelsNumber)
            </td>
            <td>
                <a onclick="showInPopup('@Url.Action("AddOrEdit", "Institutions", new { id = item.Id }, Context.Request.Scheme)' , 'Actualizar Institución')" class="btn btn-outline-secondary"><i class="fa-solid fa-pen-to-square"></i></a>
                <button data-id="@item.Id" class="btn btn-outline-danger deleteItem" data-bs-toggle="modal" data-bs-target="#deleteDialog"><i class="fa-solid fa-circle-minus"></i></button>
            </td>
        </tr>
        }
    </tbody>
</table>

SchoolAdministrator/Views/Institutions/_ViewAllLevels.cshtml
@model SchoolAdministrator.Data.Entities.Institution

<flash dismissable="true" />

<table class="table table-striped table-responsive-md table-bordered smfont text-center"  id="LevelsTable">
    <colgroup>
        <col span="1" />
        <col span="1" />
    </colgroup>
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Levels.FirstOrDefault().Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Levels.FirstOrDefault().Type)
            </th>
            <th>
                <a onclick="showInPopup('@Url.Action("AddLevel", "Institutions", new { id = Model?.Id }, Context.Request.Scheme)' , 'Nuevo Nivel')" class="btn btn-sm btn-primary text-white"><i class="fa fa-plus-circle"></i> Nivel</a>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model?.Levels)
        {
        <tr>
            <td>
                <a asp-action="DetailsLevel" asp-controller="Institutions" asp-route-Id="@item.Id">@Html.DisplayFor(modelItem => item.Name)</a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Type)
            </td>
            <td>
                <a onclick="showInPopup('@Url.Action("EditLevel", "Institutions", new { id = item.Id }, Context.Request.Scheme)' , 'Actualizar Nivel')" class="btn btn-outline-secondary"><i class="fa-solid fa-pen-to-square"></i></a>
                <button data-id="@item.Id" class="btn btn-outline-danger deleteItem" data-bs-toggle="modal" data-bs-target="#deleteDialog"><i class="fa-solid fa-circle-minus"></i></button>
            </td>
        </tr>
        }
    </tbody>
</table>